accessLog: { }

api:
  dashboard: true
  insecure: true

log:
  level: WARN

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

tls:
  certificates:
    - certFile: /ssl/localhost.pem
      keyFile: /ssl/localhost-key.pem

providers:
  docker:
    exposedByDefault: true
  file:
    filename: /etc/traefik/traefik.yaml
