accessLog: { }

api:
  dashboard: true
  insecure: true

log:
  level: WARN

entryPoints:
  web:
    address: :80

providers:
  docker:
    exposedByDefault: true
  file:
    filename: /etc/traefik/traefik.yaml