apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tic-tac-toe-certificate
  namespace: tic-tac-toe-$ENVIRONMENT
spec:
  secretName: tic-tac-toe-tls
  duration: 2160h # 90 days, maximum allowed by Let's Encrypt
  renewBefore: 360h # 15 days
  dnsNames:
    - ${INGRESS_HOST}
  issuerRef:
    name: ${CLUSTER_ISSUER_NAME}
    kind: ClusterIssuer
