apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe-deployment
  template:
    metadata:
      labels:
        app: tic-tac-toe-deployment
    spec:
      initContainers:
        - name: tic-tac-toe-migrate
          image: rutger505/tic-tac-toe-websocket:$TAG_NAME
          command:
            - "/bin/bash"
            - "-c"
            - npx prisma migrate deploy
          envFrom:
            - configMapRef:
                name: tic-tac-toe-config
            - secretRef:
                name: tic-tac-toe-secret
            - secretRef:
                name: postgres-secret
          env:
            - name: POSTGRES_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DATABASE)"

      containers:
        - name: tic-tac-toe-frontend
          image: rutger505/tic-tac-toe-frontend:$TAG_NAME
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tic-tac-toe-config
            - secretRef:
                name: tic-tac-toe-secret
            - secretRef:
                name: postgres-secret
          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DATABASE)"
        - name: tic-tac-toe-websocket
          image: rutger505/tic-tac-toe-websocket:$TAG_NAME
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: tic-tac-toe-config
            - secretRef:
                name: tic-tac-toe-secret
            - secretRef:
                name: postgres-secret
          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DATABASE)"
