apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe-deployment
  template:
    metadata:
      labels:
        app: tic-tac-toe-deployment
    spec:
      initContainers:
        - name: tic-tac-toe-migrate
          image: rutger505/tic-tac-toe-websocket:1.2.1
          command: [ "npx", "prisma", "migrate", "deploy" ]
          envFrom:
            - configMapRef:
                name: tic-tac-toe-config
            - secretRef:
                name: tic-tac-toe-secret
      containers:
        - name: tic-tac-toe-frontend
          image: rutger505/tic-tac-toe-frontend:1.2.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tic-tac-toe-config
            - secretRef:
                name: tic-tac-toe-secret
        - name: tic-tac-toe-websocket
          image: rutger505/tic-tac-toe-websocket:1.2.1
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: tic-tac-toe-config
            - secretRef:
                name: tic-tac-toe-secret
