apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-frontend-service
  namespace: tic-tac-toe-$ENVIRONMENT
spec:
  selector:
    app: tic-tac-toe-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
