apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-websocket-service
spec:
  selector:
    app: tic-tac-toe-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
