name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send Deployment Request
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"key\":\"${{ secrets.DEPLOY_KEY }}\"}" http://rutgerpronk.com:7856
