name: Deploy

#on:
#  push:
#    tags:
#      - '*'

on:
  push:
    branches:
      - migrate-to-k8s

jobs:
  deploy-database:
    uses: rutger505/kubernetes-infra/.github/workflows/deploy-database.yaml@add-database-deploy
    with:
      database: tic-tac-toe
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
      postgres_user: ${{ secrets.POSTGRES_USER }}
      postgres_password: ${{ secrets.POSTGRES_PASSWORD }}


