name: Deploy

#on:
#  push:
#    tags:
#      - '*'
on:
  push:
    branches:
      - migrate-to-k8s

jobs:
  #  deploy-database:
  #    uses: rutger505/kubernetes-infra/.github/workflows/deploy-database.yaml@add-database-deploy # TODO main
  #    with:
  #      database: tic-tac-toe
  #    secrets:
  #      kubeconfig: ${{ secrets.KUBECONFIG }}
  #      postgres_user: ${{ secrets.POSTGRES_USER }}
  #      postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
  build-front-end-docker-image:
    name: Build front-end Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push website Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: website.Dockerfile
          push: true
          tags: rutger505/tic-tac-toe-frontend:1.2.3

  build-websocket-docker-image:
    name: Build WebSocket Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push website Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: websocket.Dockerfile
          push: true
          tags: rutger505/tic-tac-toe-websocket:1.2.3

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    #    needs:
    #      - build-front-end-docker-image
    #      - build-websocket-docker-image

    steps:
      - uses: actions/checkout@v4

      - name: Install Powershell in act
        if: ${{ env.ACT }} # Powershell is not installed by default in nektos/act.
        uses: cakhanif/action-install-powershell@v1

      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v4.0.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Show files in k8s directory
        run: |
          FILES=$(ls k8s/*.yaml | tr '\n' ' ')
          
          for FILE in $FILES; do
            echo "$FILE":
            cat $FILE
          done

        # TODO switch to something without powershell dependency
      - name: Insert environment variables into Kubernetes files
        uses: jonlabelle/replace-tokens-action@v1
        with:
          paths: k8s/
          filter: "*.yaml"
          fail: true
          style: envsubst
        env:
          BASE_URL: ${{ env.BASE_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}

      - name: Show files in k8s directory
        run: |
          FILES=$(ls k8s/*.yaml | tr '\n' ' ')
          
          for FILE in $FILES; do
            echo "$FILE":
            cat $FILE
          done

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/
          images: |
            rutger505/tic-tac-toe-frontend:1.2.3
            rutger505/tic-tac-toe-websocket:1.2.3
